### ISSUE TITLE
Unit-test failure:

### ISSUE THREAD

**Issue by Fjolnir-Dvorak** [willwarren/jscp#5]
You have a hardcoded reference to your home in the unit test section:
It would be the best to use test resources deployed inside the project to allow others to verify your project.

Tests in error:
  testPwd(com.wonderant.ssh.ExecTest): java.io.FileNotFoundException: C:\cygwin\                                                                                                                                                                                               home\will.ssh\id_rsa (The system cannot find the path specified)
  testRemoteCopy(com.wonderant.ssh.JscpTest): java.io.FileNotFoundException: C:\                                                                                                                                                                                               cygwin\home\will.ssh\id_rsa (The system cannot find the path specified)
  testScpWithKey(com.wonderant.ssh.ScpTest): java.io.FileNotFoundException: C:\c                                                                                                                                                                                               ygwin\home\will.ssh\id_rsa (The system cannot find the path specified)

**Comment by codeallthethingz** [comment]
Feel free to fix! :)

**Comment by Fjolnir-Dvorak** [comment]
I will look into it.
Was there anything special about the keys?

**Comment by codeallthethingz** [comment]
Nope, they were standard generated SSH keys.  I imagine they were generated using the Github process 

``` bash
ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
```
